YNL/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import render, render_to_response

from django.template import RequestContext
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from general.views import homepage
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete



def server_error(request):
    response = render(request, "500.html")
    response.status_code = 500
    return response

#page not found
def custom_404(request):
    response = render(request, "404.html")
    response.status_co


urlpatterns = [

    
    url(r'^admin/', admin.site.urls),
    url(r'^', include("general.urls", namespace="general")),
    url(r'^backend/', include("ynladmin.urls", namespace="ynladmin")),
    url(r'^', include("wallet.urls", namespace="wallet")),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    #url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url(r'^game/', include('gameplay.urls', namespace="gameplay")),

    url(r'^mobile-validator-api/', include('mobileValidator.urls')),
    
    #change password urls
    url(r'^reset/form/$', TemplateView.as_view(template_name = 'registration/password_reset_email.html')),
    url(r'^resetpassword/passwordsent/$', password_reset_done, name="password_reset_done"),
    url(r'^resetpassword/$', password_reset, name="password_reset"),
    # url(r'^resetpassword/$', custom_password_reset, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/done/$', password_reset_complete, name="password_reset_complete"),


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

general/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views


urlpatterns = [
            url(r'^$', views.homepage, name='homepage'),
            url(r'^signup/Page/$', views.register,  name="register"),
            url(r'^login/Page/$', views.user_login,  name="login"),
            url(r'^user-logout/$', views.user_logout,  name="logout"),
            url(r'^events-page/$', views.events_page,  name="events"),
            url(r'^event/details/(?P<pk>[-\w]+)/$',views.event_details, name="event_details"),
            url(r'^user/dashboard/$',views.user_account, name = "user_account"),
            url(r'^user/profile/$',views.user_profile, name = "profile"),
            url(r'^category/(?P<value>.+)$',views.getCategory, name = "getCategory"),
            url(r'^about/$',views.about_us, name = "about_us"),
            url(r'^Contact-us/$',views.contact, name = "contact"),
            url(r'^user/messages/$',views.user_messages, name = "messages"),
            url(r'^userComment/$',views.user_comment, name = "user_comment"),
            url(r'^search-results/(?P<action>[-\w]+)/$',views.user_search, name = "user_search"),
            url(r'^user/comments/$',views.view_comment_message, name = "view_comment_message"),
            url(r'^like/comments/(?P<action>[-\w]+)/(?P<pk>.+)/$',views.like_comments, name = "like_comments"),
            url(r'^check/referral/$', views.check_referrer, name="check_referrer"),
            #url(r'^reply/comment/$', views.reply_comment,name="reply_comment"),


]

ynladmin/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views


urlpatterns = [

            # url(r'^admin/home/$', views.admin_home, name='adminHome'),
            url(r'^admin/all/(?P<pages_to>.+)/$', views.admin_pages, name='admin_pages'),
            url(r'^admin/create-event/$', views.create_new_event, name='create_new_event'),
            url(r'^admin/delete-event/(?P<event_id>[\w]+)/$', views.delete_event, name='delete_event'),
            url(r'^admin/delete-user/(?P<user_id>[\w]+)/$', views.delete_user, name='delete_user'),
            url(r'^admin/edit-event/$', views.view_edit_event, name='view_edit_event'),
            url(r'^admin/edit-user/$', views.edit_user, name='edit_user'),
            url(r'^admin/payment/(?P<status>.+)/$', views.payment_filter, name='payment_filter'),
            url(r'^admin/message/center/$', views.admin_messages, name='admin_messages'),
            url(r'^admin/delete/(?P<pk>[\w]+)/$', views.delete_message, name='delete_message'),
            url(r'^admin/archive/(?P<pk>[\w]+)/$', views.archive_message, name='archive_message'),
            url(r'^admin/event/close/(?P<event_id>[\w]+)/$', views.close_event, name='close_event'),
            url(r'^admin/deleteApprove/comment/(?P<action>.+)/(?P<pk>[\w]+)/$', views.delete_approve_comment, name='delete_approve_comment'),
            url(r'^admin/event/decision/$', views.event_decision, name='event_decision'),

    ]

general/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response, render, redirect, get_object_or_404
from django.core.serializers.json import DjangoJSONEncoder
from django.http import Http404, HttpResponse , HttpResponseRedirect, JsonResponse
from django.forms.models import model_to_dict
from general.forms import UserForm, UserAccountForm, UserProfileForm, MessageCenterCommentForm, RepliesForm
from general.models import UserAccount, Event, MessageCenter, MessageCenterComment, Comments, Likes, Replies, Referral
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required,user_passes_test
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from operator import attrgetter
from django.core import serializers
from django.db.models import Q
from django.contrib import messages
from django.template.context import RequestContext
from django.db.models import Count
from django import template
from itertools import chain
import re
import hashlib
import random, datetime
import urllib
import time
from django.core.urlresolvers import reverse
import json
from django.db.models import Sum, Max
from django.template.loader import get_template
from general.userSearch import searchQuery
from django.template import Context
from django.core.mail import EmailMessage
from django.utils import timezone
from wallet.account_standing import account_standing
from wallet.models import Bank
from gameplay.models import Gameplay
from general.staff_access import *
from django.views.decorators.csrf import csrf_exempt

# Create your views here.



def paginate_list(request, objects_list, num_per_page):
    paginator   =   Paginator(objects_list, num_per_page) # show number of jobs per page
    page  = request.GET.get('page')
    try:
        paginated_list  = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer, deliver first page
        paginated_list   =   paginator.page(1)
    except  EmptyPage:
        #if page is out of range(e.g 9999), deliver last page of results
        paginated_list      =   paginator.page(paginator.num_pages)
    return paginated_list


def getAllOpenEvent(request):
    return Event.objects.filter(deleted=False)


def homepage(request):
    context = {}
    template_name = 'general/homepage.html'
    current_time = timezone.now()
    events_all = getAllOpenEvent(request)
    query = request.GET.get('q')
    
    if query:
        events_all = events_all.filter(
                Q(title__icontains=query) |
                Q(bet_question__icontains=query) |
                Q(event_msg_body__icontains=query) |
                Q(author__first_name__icontains=query) |
                Q(author__last_name__icontains=query)
                ).distinct()
    all_events = paginate_list(request,events_all,4)
    balance = account_standing(request,request.user)
    try:
        user = UserAccount.objects.filter(user=request.user).exists()
        useraccount = user
    except:
        useraccount = None
        
        
    # print useraccount
    # categories = []
    # try:
    #     most_recent = events_all[0]
    #     context['most_recent'] = most_recent
    # except:
    #     pass
    # for event in events_all:
    #     if event.category in categories:
    #         pass
    #     else:
    #         categories.append(event.category)
    #
    
    context['trending_events'] = events_all[0:3]
    try:
        context['some_more_events'] = events_all[4]
    except:
        context['some_more_events'] = []
    context['current_time'] = current_time.date()
    context['events'] = all_events
    context['balance'] = balance
    context['useraccount']= useraccount
    return render(request, template_name, context)



def getCategory(request,value):
    context = {}
    balance = account_standing(request,request.user)
    context['balance'] = balance
    template_name = 'general/events-page.html'
    value_to_upperCase = value.upper()
    events_all = Event.objects.filter(deleted=False,category=value_to_upperCase)
    datalist = getAllOpenEvent(request).values_list('title', flat=True).distinct()
    new_datalist = ",".join([str(item) for item in datalist])
    all_events = paginate_list(request,events_all,12)
    categories = []
    print new_datalist
   
    for event in events_all:
        if event.category in categories:
            pass
        else:
            categories.append(event.category)
    context['categories'] = categories
    context['all_events'] = all_events
    context['datalist'] = new_datalist
    return render(request, template_name, context)



def user_login(request):
    if request.method == "POST":
        #print request.POST
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            username = User.objects.get(email=username).username
            print username
        except Exception as e:
            print "e", e
            try:
                username = User.objects.get(username=username).username
                print username
                username = username
            except Exception as e:
                messages.warning(request,"Invalid login details supplied")
                return redirect(reverse('general:login'))
        user = authenticate(username=username, password=password)
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
    
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                print "I got here"
                if user.is_staff:
                    print "I am a staff"
                    response =  redirect(reverse('ynladmin:admin_pages', args=['events']))
                    return response    
                else:
                    response = redirect(reverse('general:events'))
                    return response
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            messages.warning(request,"Invalid login details supplied")
            return redirect(reverse('general:login'))

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'general/sign_in.html', {})



@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return redirect(reverse('general:homepage'))



def register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        rp = request.POST
        print rp
        #print "form", form
    	if User.objects.filter(username = rp.get('username')).exists():
    		print 'username exists'
    		return render(request, 'general/registration.html', {'form': form,'username_is_taken':True})                
    	if User.objects.filter(email = rp.get('email')).exists():
    		print 'email exists'                
    		return render(request, 'general/registration.html', {'form': form,'email_taken':True})                
    	else:
    		if form.is_valid():
    			user = form.save(commit=False)
    			password  = rp.get('password')
    			password1   = rp.get('password1')
    			if password != password1:
    				return render(request, 'general/registration.html', {'form': form,'password_mismatch':True})
    			if len(password) < 8:
    				return render(request, 'general/registration.html', {'form': form,'password_too_short':True})
    			# if password == rp.get('first_name'):
    			# 	return render(request, 'general/registration.html', {'form': form,'password_same_as_first_name':True})
    			if password.isalpha():
    				return render(request, 'general/registration.html', {'form': form,'password_should_be_alphanumeric':True})
    			# user = User.objects.create(username = rp.get('username'), email = rp.get('email').lower(),
    			# 	first_name = rp.get('first_name'), last_name = rp.get('last_name'))
    			user.set_password(user.password)
    			user.save()
    			''' try this '''
    			# new_user_acc_obj = UserAccount.objects.create(user=user)
    			messages.success(request,"Registration was successful")
    			return redirect('general:login')
    		else:
    			print form.errors
    else:
    	form = UserForm()
    return render(request, 'general/registration.html', {'form': form})



def get_simillar_values(request):
    events_all = getAllOpenEvent(request)
    datalist = events_all.values_list('title', flat=True).distinct()
    new_datalist = ",".join([str(item) for item in datalist])
    return events_all, new_datalist



def events_page(request):
    context = {}
    
    balance = account_standing(request,request.user)
    context['balance'] = balance
    
    current_time = timezone.now()
    events_all,new_datalist = get_simillar_values(request)

    all_events = paginate_list(request,events_all,12)
    context['all_events'] = all_events
    context['datalist'] = new_datalist
    context['current_time'] = current_time
        
    return render(request, 'general/events-page.html', context)



def event_details(request,pk):
    context = {}
    events_all = getAllOpenEvent(request)
    categories = []
    balance = account_standing(request,request.user)
    for event in events_all:
        if event.category in categories:

general/templates/general_snippets/decison_modal.html
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Event Decision</h4>
      </div>
      <div class="modal-body">
        <h5>
          {{event.bet_question}}
        </h5>
        <div>
          <form action="{% url 'ynladmin:event_decision' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <!--label class="control-label">Event Decision</label>-->
              {{ form.event_decision }}
            </div>
            <div class="hidden">
              <input type="text" name="event_id" value="{{event.id}}"/>
            </div>
            <button class = "pull-right"type="submit">Submit</button>
          </form>
        </div>
      </div>
      <div class="modal-footer">
        <!--<button type="button" class="btn btn-default" data-dismiss="modal"></button>-->
      </div>
    </div>

  </div>
</div>

general/templates/general_snippets/general_modals.html
<div class="modal fade" id="userMessagesForm" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <!-- Modal Header -->
            <div class="modal-header" style="background-color: azure;">
                <button type="button" class="close" 
                   data-dismiss="modal">
                       <span aria-hidden="true">&times;</span>
                       <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Send Message
                </h4>
            </div>
            
            <!-- Modal Body -->
            <div class="modal-body" style="background-color: azure;">
                
                <form name="create_event" id="create_event" method="POST" action="{% url 'general:messages' %}" 
				  enctype="multipart/form-data">
				  {% csrf_token %}

				  		<p>NB: Fields with <b style="color:red">'*'</b> are required</p>

				  		<div class="form-group">
			  			<label class="label-controller">Subject</label><br/>
			  			<input type="text" class=" form-control" name="subject" required id="subject" value="">
				  		</div>

						<div class="form-group">
						<label class="label-controller">Message</label><br/>
						{{comment_form.message}}
						</div><br/>

						<div class="form-group">
						<label>Upload Image</label>
						{{comment_form.image_obj}}
						</div>

					    <button type="submit" id="userMessage" class="btn btn-success pull-right">Submit</button><br/>

					</form>         
        	</div>
        </div>
    </div>
</div>


<div class="modal fade" id="messageToComment" tabindex="-1" role="dialog" 
		aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="messageComment">
        </div>
    </div>
</div>


<div class="modal fade" id="viewMessage" tabindex="-1" role="dialog" 
		aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="messageView">
        </div>
    </div>
</div>

general/templates/general_snippets/messageComments.html
<div class="modal-content" id="messageComment">
{% include 'general/special_styles.html' %}

    <!-- Modal Header -->
    <div class="modal-header"  style="background-color: azure;">
        <button type="button" class="close" 
           data-dismiss="modal">
               <span aria-hidden="true">&times;</span>
               <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
            Send your complaints
        </h4>
        <p> <b>NOTE:</b> The use of <span style="color:red;">foul languauge and abuse speech</span> is highly prohibited and will lead to blocking of account if investigated by admin and establisehd to be true</p>
    </div>
    

    <!-- Modal Body -->
    <div class="modal-body" id="support_all_messages" style="background-color: azure;">
        <div class="all_comms" style="overflow: scroll; margin-bottom: 10px;  height: 250px;" >

            {% for message in all_comments %}
                <div class="the_message">
                {% if message.user.is_staff %}
                    <span class="shape_oval_orange" style="position: relative; top: 15px;"></span>
                    <span style="position: relative; left: 20px;">Admin</span><br/>
                {% else %}
                    <span class="shape_oval_green" style="position: relative; top: 15px;"></span>
                    <span style="position: relative; left: 20px;">{{message.user}}</span><br/>
                {% endif %}
                    <span>{{message.message}}</span><br/>
                    <span>{{message.date}}</span><br/>
                    {% if message.image_obj %}
                    <span><a href="{{message.image_obj.url}}">image</a></span>
                    {% endif %}
                </div><hr>
            {% endfor %}
        </div>

        <div class="comms_all">
            <div class="the_values">
                <form method="POST" id="post-forms" class="post-forms"  method="POST" action="{% url 'general:view_comment_message' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label class="label-controller">Message</label><br/>
                        {{ comment_form.message }}
                    </div><br/>
                    <div class="fieldWrapper">
                        <label>Upload image</label><br/>
                        {{ comment_form.image_obj }}
                    </div>
                    <input type="hidden" name="msg_id" id="msg_id" value="{{message_id}}">
                    <input class="pull-right btn2" type="submit" value="Submit" class="tiny button">
                </form>
            </div>
        </div>
    </div>


    <!-- Modal Footer -->
    <div class="modal-footer"  style="background-color: azure;">
       
    </div>

</div>

general/templates/general_snippets/referral_modal.html
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Referrals</h4>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
          <table class="table table-striped">
              <thead>
                  <tr>
                      <th>First Name</th>
                      <th>Last Name</th>
                  </tr>
              </thead>
              <tbody>
                {% for user in referral.all_users %}
                <tr>
                  <td>{{user.user.first_name}}</td>
                 <td>{{user.user.last_name}}</td>
                </tr>
                {% endfor %}
              </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

general/templates/general_snippets/reply.html
                                                <div id="commentsection">
												{% if comment.get_all_replies %}
												{% for reply in comment.get_all_replies %}
												<div class="comment-reply">
													<img src="{% static 'img/blog/comment_2.jpg' %}" class="comment-avatar" alt="">
													<div class="comment-content">
														<span class="comment-author">{{ reply.user }}</span>
														<span><a href="#">{{ reply.created_on }}</a></span>		
														<p>{{ reply.reply }}</p>
													</div>

												</div>
												{% endfor %}
												{% endif %}
													

												{% endfor %}
												</div>

general/templates/general_snippets/viewMessages.html
<div class="modal-content" id="messageView">
{% include 'general/special_styles.html' %}

    <!-- Modal Header -->
    <div class="modal-header"  style="background-color: azure;">
        <button type="button" class="close" 
           data-dismiss="modal">
               <span aria-hidden="true">&times;</span>
               <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
            Send your complaints
        </h4>
        <p> <b>NOTE:</b> The use of <span style="color:red;">foul languauge and abuse speech</span> is highly prohibited and will lead to blocking of account if investigated by admin and establisehd to be true</p>
    </div>
    

    <!-- Modal Body -->
    <div class="modal-body" id="support_all_messages" style="background-color: azure;">
        <div class="all_comms" style="overflow: scroll; margin-bottom: 10px;  height: 250px;" >

            {% for message in all_comments %}
                <div class="the_message">
                {% if message.user.is_staff %}
                    <span class="shape_oval_orange" style="position: relative; top: 15px;"></span>
                    <span style="position: relative; left: 20px;">Admin</span><br/>
                {% else %}
                    <span class="shape_oval_green" style="position: relative; top: 15px;"></span>
                    <span style="position: relative; left: 20px;">{{message.user}}</span><br/>
                {% endif %}
                    <span>{{message.message}}</span><br/>
                    <span>{{message.date}}</span><br/>
                    {% if message.image_obj %}
                    <span><a href="{{message.image_obj.url}}">image</a></span>
                    {% endif %}
                </div><hr>
            {% endfor %}
        </div>
    </div>


    <!-- Modal Footer -->
    <div class="modal-footer"  style="background-color: azure;">
       
    </div>

</div>