YNL/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import render, render_to_response

from django.template import RequestContext
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from general.views import homepage
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete



def server_error(request):
    response = render(request, "500.html")
    response.status_code = 500
    return response

#page not found
def custom_404(request):
    response = render(request, "404.html")
    response.status_co


urlpatterns = [

    
    url(r'^admin/', admin.site.urls),
    url(r'^', include("general.urls", namespace="general")),
    url(r'^backend/', include("ynladmin.urls", namespace="ynladmin")),
    url(r'^', include("wallet.urls", namespace="wallet")),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    #url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url(r'^game/', include('gameplay.urls', namespace="gameplay")),

    url(r'^mobile-validator-api/', include('mobileValidator.urls')),
    
    #change password urls
    url(r'^reset/form/$', TemplateView.as_view(template_name = 'registration/password_reset_email.html')),
    url(r'^resetpassword/passwordsent/$', password_reset_done, name="password_reset_done"),
    url(r'^resetpassword/$', password_reset, name="password_reset"),
    # url(r'^resetpassword/$', custom_password_reset, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/done/$', password_reset_complete, name="password_reset_complete"),


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gameplay/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views


urlpatterns = [
        url(r'^betting/$',views.betting, name = "betting"),
]

wallet/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views


urlpatterns = [
        url(r'^wallet/details/$',views.view_wallet, name="wallet"),
        url(r'^wallet/topup/$',views.main, name="main"),
        url(r'^verify/payment/$',views.verify_payment, name="verify_payment"),
       # url(r'^create/recipient/$',views.create_recipient, name="recipient"),
        url(r'^wallet/resend/otp/$',views.resend_otp, name="resend_otp"),
        url(r'^wallet/cashout/$',views.cash_out, name="cashout"),
        url(r'^wallet/initiate-transfer/$',views.initiate_transfer, name="initiate_transfer"),
        url(r'^wallet/finalize-transfer/$',views.finalize_transfer, name="finalize_transfer"),
        


]

ynladmin/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views


urlpatterns = [

            # url(r'^admin/home/$', views.admin_home, name='adminHome'),
            url(r'^admin/all/(?P<pages_to>.+)/$', views.admin_pages, name='admin_pages'),
            url(r'^admin/create-event/$', views.create_new_event, name='create_new_event'),
            url(r'^admin/delete-event/(?P<event_id>[\w]+)/$', views.delete_event, name='delete_event'),
            url(r'^admin/delete-user/(?P<user_id>[\w]+)/$', views.delete_user, name='delete_user'),
            url(r'^admin/edit-event/$', views.view_edit_event, name='view_edit_event'),
            url(r'^admin/edit-user/$', views.edit_user, name='edit_user'),
            url(r'^admin/payment/(?P<status>.+)/$', views.payment_filter, name='payment_filter'),
            url(r'^admin/message/center/$', views.admin_messages, name='admin_messages'),
            url(r'^admin/delete/(?P<pk>[\w]+)/$', views.delete_message, name='delete_message'),
            url(r'^admin/archive/(?P<pk>[\w]+)/$', views.archive_message, name='archive_message'),
            url(r'^admin/event/close/(?P<event_id>[\w]+)/$', views.close_event, name='close_event'),
            url(r'^admin/deleteApprove/comment/(?P<action>.+)/(?P<pk>[\w]+)/$', views.delete_approve_comment, name='delete_approve_comment'),
            url(r'^admin/event/decision/$', views.event_decision, name='event_decision'),

    ]

ynladmin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class CostSetting(models.Model):
    """ The stakeholders cost in percentage """
    amount   = models.IntegerField()
    
    
    def __unicode__(self):
        return '%s' %(self.amount)

ynladmin/forms.py
from ynladmin.models import CostSetting
from django import forms

class CostSettingForm(forms.ModelForm):
    amount   = forms.IntegerField(help_text="Amount", required = True, widget=forms.NumberInput(attrs={'class':'form-control','required':'required', 'placeholder':'Amount(%)','max':'50'}))
       
    class Meta:
        model = CostSetting
        fields = ('amount',)

gameplay/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from general.models import Event, UserAccount
from django.shortcuts import render, redirect
from wallet.account_standing import account_standing
from django.utils import timezone
from wallet.models import Bank, Betpayments
from wallet.views import generate_purchaseRef, purchase_ref
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from gameplay.models import Gameplay
from django.core.urlresolvers import reverse
# Create your views here.


@login_required
def betting(request):
    balance = account_standing(request, request.user)
    if request.method == "POST":
        print request.POST
        amount = float(request.POST.get('amount'))
        if amount > balance :
            messages.error(request, "You do not have sufficient money in your wallet to place that bet")
            return redirect(request.META['HTTP_REFERER'])
        else:
            choice = str(request.POST.get('user-choice'))
            print 'choice',choice
            event = Event.objects.get(id=request.POST.get('event'))
            user = UserAccount.objects.get(user=request.user)
            try:
                gameplay = Gameplay.objects.get(event=event, user=user)
                print gameplay
                messages.warning(request, "You have already Participated in this Event")
                return redirect(request.META['HTTP_REFERER'])
            except Exception as e:
                print "e",e
            gameplay = Gameplay.objects.create(user=user,event=event,amount=amount,choice=choice,date=timezone.now(),status="OPEN")
            gameplay.save()
            event.total_amt += amount
            event.counter += 1
            event.save()
            random_ref = purchase_ref()
            bank_record = Bank.objects.create(user=request.user,txn_type="Remove",amount=amount, ref_no=random_ref,
                        created_at=timezone.now(), status="Successful", bank="Gameplay", message="Gameplay")
            bank_record.save()
            payment = Betpayments.objects.create(user=request.user,amount=amount,game=gameplay,date=timezone.now())
            payment.save()
            messages.success(request, 'Congratulations!!!! You have successfully placed your bet.')
            return redirect(request.META['HTTP_REFERER'])
    return redirect(reverse('general:homepage'))
            

ynladmin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.http import HttpResponse
from django.shortcuts import render_to_response, render, redirect, get_object_or_404
from django.core.serializers.json import DjangoJSONEncoder
from django.http import Http404, HttpResponse , HttpResponseRedirect, JsonResponse
from django.forms.models import model_to_dict
from wallet.models import Bank
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required,user_passes_test
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth.models import User
from operator import attrgetter
from django.core import serializers
from django.db.models import Q
from django.contrib import messages
from django.template.context import RequestContext
from django.db.models import Count
from django import template
from itertools import chain
import re
import hashlib
import random, datetime, string
import urllib
import time, math
from django.core.urlresolvers import reverse
import json
from django.db.models import Sum
from django.template.loader import get_template
from django.template import Context
from django.core.mail import EmailMessage
from general.models import *
from general.forms import *
from general.views import paginate_list
from gameplay.models import Gameplay
from wallet.models import Bank
from ynladmin.models import CostSetting
from ynladmin.forms import CostSettingForm
from wallet.views import purchase_ref, generate_purchaseRef

# Create your views here.



def randomNumber(value):
	allowed_chars = ''.join((string.digits))
	unique_id = ''.join(random.choice(allowed_chars) for _ in range(5))
	return '#' + 'EN' + unique_id


# @login_required
# def admin_home(request):
# 	context = {}
# 	template_name = 'ynladmin/adminHome.html'
# 	user_obj = request.user
# 	user_acc_obj = UserAccount.objects.get(user=user_obj)
# 	context['user_acc_obj'] = user_acc_obj
# 	return render(request,template_name,context)


@login_required
def admin_pages(request,pages_to):
	context = {}
	user_obj = request.user
	try:
		user_acc_obj = UserAccount.objects.get(user=user_obj)
	except:
		return redirect(request.META['HTTP_REFERER'])
	context['user_acc_obj'] = user_acc_obj
	if pages_to == 'events':
		events = Event.objects.filter(deleted=False)
		query = request.GET.get('q')
		if query:
			print "query", query
			events = events.filter(
				Q(title__icontains=query)|
				Q(category__icontains=query)|
				Q(bet_question__icontains=query)|
				Q(event_msg_body__icontains=query) |
				Q(event_id__icontains=query)|
				Q(author__first_name__icontains=query)
				).distinct()
			print events
		all_event = paginate_list(request,events,10)
		template_name = 'ynladmin/events.html'
		event_form = EventForm()
		context['event_form'] = event_form
		context['all_events'] = all_event
	elif pages_to == 'users':
		template_name = 'ynladmin/users.html'
		users = UserAccount.objects.filter(deleted=False)
		query = request.GET.get('q')
		if query:
			print "query", query
			users = users.filter(
				Q(user__first_name__icontains=query) |
				Q(bank__icontains=query) |
				Q(user__last_name__icontains=query) |
				Q(phone_number__icontains=query) |
				Q(gender__icontains=query) |
				Q(account_number__icontains=query)
				)
		all_users = paginate_list(request,users,10)
		useraccount_form = UserAccountForm()
		user_form = UserForm()
		context['useraccount_form'] = useraccount_form
		context['all_users'] = all_users
		context['user_form'] = user_form
	elif pages_to == 'messages':
		template_name = 'ynladmin/messages.html'
		messages = MessageCenter.objects.all()
		query = request.GET.get('q')
		if query:
			new_messages = messages.filter((Q(subject__icontains=query) | Q(user__username__icontains=query)), new=True)
			replied_messages = messages.filter((Q(subject__icontains=query) | Q(user__username__icontains=query)), replied=True)
			archived_messages = messages.filter((Q(subject__icontains=query) | Q(user__username__icontains=query)), archive=True)
			deleted_messages = messages.filter((Q(subject__icontains=query) | Q(user__username__icontains=query)), deleted=True)
		else:
			new_messages = messages.filter(new=True)
			replied_messages = messages.filter(replied=True)
			archived_messages = messages.filter(archive=True)
			deleted_messages = messages.filter(deleted=True)
		comment_form = MessageCenterCommentForm()
		context['comment_form'] = comment_form
		context['new_messages'] = new_messages
		context['replied_messages'] = replied_messages
		context['archived_messages'] = archived_messages
		context['deleted_messages'] = deleted_messages
		context['new_count'] = new_messages.count()
		context['replied_count'] = replied_messages.count()
		context['archived_count'] = archived_messages.count()
		context['deleted_count'] = deleted_messages.count()
	elif pages_to == "payment":
		template_name = 'ynladmin/payment.html'
		payment = Bank.objects.all()
		query = request.GET.get('q')
		if query:
			print "query", query
			payment = payment.filter(
				Q(user__first_name__icontains=query) |
				Q(bank__icontains=query) |
				Q(user__last_name__icontains=query) |
				Q(ref_no__icontains=query)
				)
		payments = paginate_list(request,payment,10)
		context['payments'] = payments
	elif pages_to == "comments":
		template_name = 'ynladmin/comments.html'
		comments = paginate_list(request,Comments.objects.all(),10)
		context['comments'] = comments
	elif pages_to == "game":
		template_name = 'ynladmin/gameplay.html'
		events = Event.objects.all()
		query = request.GET.get('q')
		if query:
			print "query", query
			events = events.filter(
				Q(event_id__icontains=query)) 
		event = paginate_list(request,events,10)
		context['event'] = event
	elif pages_to == "settings":
		if request.method == "POST":
			try:
				cost = CostSetting.objects.get(id=1)
				form = CostSettingForm(request.POST, instance=cost)
			except:
				form = CostSettingForm(request.POST)
			if form.is_valid():
				form.save()
				#messages.success(request,"Amount Updated Successfully")
			else:
				print form.errors
				messages.error(request,"Please try again")
		template_name = 'ynladmin/settings.html'
		try:
			cost = CostSetting.objects.get(id=1)
			form = CostSettingForm(instance=cost)
		except:
			form = CostSettingForm()
		context['form']=form
	return render(request,template_name,context)


@login_required
def create_new_event(request):
	print "i got here"
	context = {}
	user_obj = request.user
	user_acc_obj = UserAccount.objects.get(user=user_obj)
	event_form = EventForm()
	all_event = paginate_list(request,Event.objects.filter(deleted=False),10)
	context['event_form'] = event_form
	context['all_events'] = all_event
	context['user_acc_obj'] = user_acc_obj
	template_name = 'ynladmin/events.html'
	if request.method == 'POST':
		rp = request.POST
		print 'rp:', rp
		if rp.has_key('edit_event'):
			print "i wanna edit"
			event_obj = Event.objects.get(event_id=rp.get('event_track_num'))
			form = EventForm(request.POST, request.FILES, instance=event_obj)
			if form.is_valid():
				print 'The form is valid'

				start_date = rp.get('start_date')
				end_date = rp.get('end_date')
				start_time = rp.get('start_time')
				end_time = rp.get('end_time')
				
				if start_date > end_date:
					messages.warning(request,'Unsuccessful...Start date cannot be less than or equal to end date')
					return redirect(request.META['HTTP_REFERER'])
				if start_date == end_date:
					if start_time == end_time:
						messages.warning(request,'Unsuccessful...Start time cannot be equal to or less than end time')
						return redirect(request.META['HTTP_REFERER'])
				else:
					print "you may proceed"
					create_event_form = form.save(commit=False)
					#create_event_form.event_msg_body = str(re.sub('<[^<]+?>', '', rp.get('event_msg_body'))).replace('&nbsp;','')
					print "the message:",create_event_form.event_msg_body
					create_event_form.author = request.user
					create_event_form.event_id = rp.get('event_track_num')
					create_event_form.save()
					messages.success(request,'Event has been successfully updated')
					return redirect(reverse('ynladmin:admin_pages', args=['events']))
			else:
				print form.errors
		elif rp.has_key('edit_user'):
			print "i wanna edit this user"
			user_obj = UserAccount.objects.get(id=rp.get('user_id'))
			form = UserAccountForm(request.POST, request.FILES, instance=user_obj)
			if form.is_valid():
				print 'The form is valid'
				form.save()
				return redirect(reverse('ynladmin:admin_pages', args=['users']))
			else:
				print form.errors
		else:
			form = EventForm(request.POST, request.FILES)
			if form.is_valid():
				print 'The form is valid'

				start_date = rp.get('start_date')
				end_date = rp.get('end_date')
				start_time = rp.get('start_time')
				end_time = rp.get('end_time')
				
				if start_date > end_date:
					messages.error(request,'Unsuccessful...Start date cannot be less than or equal to end date')
					return redirect(request.META['HTTP_REFERER'])
				if start_date == end_date:
					if start_time == end_time:
						messages.error(request,'Unsuccessful...Start time cannot be equal to or less than end time')
						return redirect(request.META['HTTP_REFERER'])	
				else:
					#pass
					create_event_form = form.save(commit=False)
					#create_event_form.event_msg_body = str(re.sub('<[^<]+?>', '', rp.get('event_msg_body'))).replace('&nbsp;','')
					create_event_form.author = request.user
					create_event_form.event_id = randomNumber(str(rp.get('category'))[:2])
					create_event_form.save()
					messages.success(request,'Event has been successfully created')
					return redirect(reverse('ynladmin:admin_pages', args=['events']))
			else:
				print form.errors
			return render(request,template_name,context)
		return render(request,template_name,context)
	else:
		return render(request,template_name,context)


@login_required

ynladmin/templates/ynladmin/adminmessageComments.html
<div class="modal-content" id="adminmessageComment">
{% include 'general/special_styles.html' %}

    <!-- Modal Header -->
    <div class="modal-header"  style="background-color: azure;">
        <button type="button" class="close" 
           data-dismiss="modal">
               <span aria-hidden="true">&times;</span>
               <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
            Respond to complaints
        </h4>
        <p> <b>NOTE:</b> The use of <span style="color:red;">foul languauge and abuse speech</span> is highly prohibited and will lead to blocking of account if investigated by admin and establisehd to be true</p>
    </div>
    

    <!-- Modal Body -->
    <div class="modal-body" id="support_all_messages" style="background-color: azure;">
        <div class="all_comms" style="overflow: scroll; margin-bottom: 10px;  height: 250px;" >

            {% for message in all_comments %}
                <div class="the_message">
                {% if message.user.is_staff %}
                    <span class="shape_oval_orange" style="position: relative; top: 15px;"></span>
                    <span style="position: relative; left: 20px;">Admin</span><br/>
                {% else %}
                    <span class="shape_oval_green" style="position: relative; top: 15px;"></span>
                    <span style="position: relative; left: 20px;">{{message.user}}</span><br/>
                {% endif %}
                    <span>{{message.message}}</span><br/>
                    <span>{{message.date}}</span><br/>
                    {% if message.image_obj %}
                    <span><a href="{{message.image_obj.url}}">image</a></span>
                    {% endif %}
                </div><hr>
            {% endfor %}
        </div>

        <div class="comms_all">
            <div class="the_values">
                <form method="POST" id="post-forms" class="post-forms"  method="POST" action="{% url 'ynladmin:admin_messages' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label class="label-controller">Message</label><br/>
                        {{ comment_form.message }}
                    </div>
                    <div class="fieldWrapper">
                        <label>Upload image</label><br/>
                        {{ comment_form.image_obj }}
                    </div>
                    <input type="hidden" name="msg_id" id="msg_id" value="{{message_id}}">
                    <input class="pull-right btn2" type="submit" value="Submit" class="tiny button">
                </form>
            </div>
        </div>
    </div>


    <!-- Modal Footer -->
    <div class="modal-footer"  style="background-color: azure;">
       
    </div>

</div>

ynladmin/templates/ynladmin/events.html
{% extends 'ynladmin/adminHome.html' %}
{% load staticfiles %}


{% block add_event %}
<h4 class="pull-right"  style="cursor: pointer; color: #449f07;" id="add_event"><i class="fa fa-plus">&nbsp;ADD EVENT</i></h4>
{% endblock add_event %}

{% block events_won %}
{% endblock events_won %}

{% block transactions %}

	
<div class="col-md-12 view-events">
<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <!--<h3 style="margin:15px 0px 5px 0px;">

                % for msg in messages %}
                    <script>
                        function show_alert(){
                        var alert = '<p style="color:red;" class="text-{ msg.tags }} bg-{{ msg.tags }}">{{ msg }}</p>';
                        document.write(alert);
                        }
                        display = window.setTimeout(show_alert(), 1000);
                        window.clearTimeout(display);
                    </script>
                % endfor %}
            </h3>-->
            <h3 class="box-title">Event Manager</h3>
            <div class="table-responsive">
                <table border="0" class="table table-striped" >
                    <thead>
                        <tr>
                            <th>Event ID</th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Start Date</th>
                            <th>End Date</th>
<!--                             <th>Closed</th>
 -->                        <th>Action</th>
							<th>Status</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                    {% for event in all_events %}
                        <tr>
                            <td>{{event.event_id}}</td>
                            <td>{{event.title}}</td>
                            <td>{{event.category}}</td>
                            <td>{{event.start_date}}</td>
                            <td>{{event.end_date}}</td>
<!--                             <td>{event.closed}}</td>
 -->                            <td>
                                <span><a class="view_event" identifier="view" event_track_num="{{event.event_id}}"><i class="fa fa-eye"  title="View"
                                style="cursor: pointer;"></i></a>
                                </span>&nbsp;&nbsp;
								
								{% if not event.closed %}
									{% if not event.publish %}
										<span><a class="edit_event" identifier="edit" event_track_num="{{event.event_id}}"><i class="fa fa-pencil" title="Edit" 
										style="cursor: pointer;"></i></a>
										</span>&nbsp;&nbsp;
										<span><a style="cursor: pointer;" href="{% url 'ynladmin:delete_event' event.id %}" onclick="return confirm('Are you sure you want to delete this event?')"><i class="fa fa-trash" title="Delete"></i></a>
										</span>
									{% elif not event.decided %}
										<span><a class="decision" event_track_num="{{event.id}}"><i class="fa fa-gavel" aria-hidden="true"
										style="cursor: pointer;"></i></a>
									{% endif %}
								{% endif %}
								
                                
                            </td>
							<td>{% if event.closed %}<i class="fa fa-lock" aria-hidden="true"></i>{% elif not event.closed and event.decided %} <span><a style="cursor: pointer;" href="{% url 'ynladmin:close_event' event.id %}"
							onclick="return confirm('Are you sure you want to CLOSE this Event?')"><i class="fa fa-unlock-alt" aria-hidden="true"></i>{% endif %}</a></span></td>
                        </tr>
                    {% empty %}
                        <p>No Event</p>
                    {% endfor %}  
                    </tbody>
                    
                </table>

            <div class="pagination" style="position:relative; font-size:20px; margin:0px; left:500px;">
                <span class="step-links">
                    {% if all_events.has_previous %}
                        <a style="font-size:20px;" href="?page={{ all_events.previous_page_number }}">&laquo;</a>
                    {% else %}
                        <a style="font-size:20px;" class="hidden" >&laquo;</a>

                    {% endif %}

                    <span style="font-size:20px;" class="current">
                        Page {{ all_events.number }} of {{ all_events.paginator.num_pages }}.
                    </span>

                    {% if all_events.has_next %}
                        <a style="font-size:20px;" href="?page={{ all_events.next_page_number }}">&raquo;</a>
                    {% else %}
                        <a style="font-size:20px;" class="hidden">&raquo;</a>

                    {% endif %}
                </span>
            </div>
            </div>
        </div>
    </div>
</div>
</div>
	
{% endblock transactions %}

ynladmin/templates/ynladmin/payment.html
{% extends 'ynladmin/adminHome.html' %}
{% load staticfiles %}
{% load humanize %}

{% block add_event %}

{% endblock add_event %}

{% block events_won %}
<div class="dropdown pull-right" style="position: relative;bottom: 10px;">
    <button class="btn btn-primary dropdown-toggle" style="background: #449f07!important;" type="button" data-toggle="dropdown">Filter By:
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><a href="{% url 'ynladmin:payment_filter' 'successful' %}">Successful</a></li>
      <li><a href="{% url 'ynladmin:payment_filter' 'declined' %}">Declined</a></li>
      <li><a href="{% url 'ynladmin:payment_filter' 'transfer' %}">Transfer</a></li>
    </ul>
  </div>
{% endblock events_won %}

{% block transactions %}

<div class="col-md-12 view-events">
<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <h3 class="box-title">Payment Manager</h3>
            <div class="table-responsive">
                <table border="0" class="table table-striped" >
                    <thead>
                        <tr>
                            <!--<th>User ID</th>-->
                            <th>S/N</th>
                            <th>Ref No</th>
							<th>Name</th>
                            <th>Bank</th>
                            <th>Description</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                    {% for payment in payments %}
                        <tr>
                            <!--<td>{user.pk}}</td>-->
                            <td>{{forloop.counter}}</td>
                            <td>{{payment.ref_no}}</td>
							<td>{{payment.user.last_name}}</td>
                            <td>{{payment.bank}}</td>
                            <td>{{payment.message}}</td>
                            <td>₦{{payment.amount|floatformat:2|intcomma}}</td>
                            <td>{{payment.status}}</td>
                            
                            <td>
                                {% if payment.status == "Transfer" %}
                                <span><a id="transfer" user_id="{{payment.pk}}"><i class="fa fa-money" aria-hidden="true"  
                                style="cursor: pointer;"></i></a></span>
                                {% else %}
                                <span><a style="cursor: pointer;"><i class="fa fa-columns"></i></a></span>
                                {% endif %}
                            </td>
                            
                        </tr>
                    {% empty %}
                        <p>No Payment Record found!!!!</p>
                    {% endfor %}  
                    </tbody>
                    
                </table>

                <div class="pagination" style="position:relative; font-size:20px; margin:0px; left:500px;">
                <span class="step-links">
                    {% if payments.has_previous %}
                        <a style="font-size:20px;" href="?page={{ payments.previous_page_number }}">&laquo;</a>
                    {% else %}
                        <a style="font-size:20px;" class="hidden" >&laquo;</a>

                    {% endif %}

                    <span style="font-size:20px;" class="current">
                        Page {{ payments.number }} of {{ payments.paginator.num_pages }}.
                    </span>

                    {% if payments.has_next %}
                        <a style="font-size:20px;" href="?page={{ payments.next_page_number }}">&raquo;</a>
                    {% else %}
                        <a style="font-size:20px;" class="hidden">&raquo;</a>

                    {% endif %}
                </span>
            </div>
            </div>
        </div>
    </div>
    <div class="loader hidden"></div>
</div>
</div>
	<!--<div class="loader hidden"></div>-->
{% endblock transactions %}

{% block modals %}
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">OTP</h4>
      </div>
      <div class="modal-body">
        <div class="container be-detail-container" id="otp">
        
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% endblock modals %}

{% block customscripts %}

<script>
    $('body').on('click','#transfer', function(){
        $('.loader').removeClass('hidden');
        var pk = $(this).attr('user_id');
        console.log(pk);
        $.ajax({
            url: "{% url 'wallet:initiate_transfer' %}",
            type: 'GET',
            data: {'pk': pk},
            success: function(data){
                $('.loader').addClass('hidden');
                $('#otp').replaceWith(data);
                $('#myModal').modal('show');
                 },
            error: function(data){
                console.log('not working');
            }
        });
        });
</script>

<script>
    $('body').on('click','#resend_otp', function(){
        //$('.loader').removeClass('hidden');
        var code = $('#transfer_code').val();
        //console.log(pk);
        $.ajax({
            url: "{% url 'wallet:resend_otp' %}",
            type: 'GET',
            data: {'code': code},
            success: function(data){
                alert('OTP has been resent');
                //$('.loader').addClass('hidden');
                //$('#otp').replaceWith(data);
                //$('#myModal').modal('show')*/;
                 },
            error: function(data){
                console.log('not working');
            }
        });
        })
</script>

{% endblock customscripts %}